name: Deploy Daraja Plugin to cPanel

on:
  push:
    branches:
      - main  # or the branch you’re deploying from

jobs:
  ftp-deploy:
    name: Upload plugin via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /public_html/payment/wp-content/plugins/daraja-api/
          local-dir: daraja-api/
